### ISSUE TITLE
No Way To Create A Recipe For Water Bottle

### ISSUE THREAD

**Issue by ghost** [ezterry/JsonRecipeEdit#2]
i spent 3 hours but couldn't make a recipe for water bottle. Can you try it? for example, ingredient is water bucket, and the output is water bottle. If you could manage to do it, can you tell me the code? Because it's giving me "Uncraftable potion". Please help. Thanks.

**Comment by ghost** [comment]
okay, i got it with this code:
    **`"result":["minecraft:potion",0,"{Potion:\"minecraft:water\"}"]`**
i just wonder, why did you add that "\\" to the code? this code ( **{Potion:\"minecraft:water\"}** ) in normal minecraft is like this:
{Potion:"minecraft:water"}
i just wonder, why? 
i spent totally 4 hours to solve it. but solved, so happy.

**Comment by ezterry** [comment]
Its a json list [item,meta,nbt] the nbt data is json-ish .. but not actually json .. so I need the nbt as a string that I pass to the same logic /give uses to read the nbt data.

thus the string:  {Potion:"minecraft:water"}
has to be escaped to be read in properly:  "{Potion:\\"minecraft:water\\"}"


Thus to have a shapeless craft 1 bucket water + bottle = water bottle:
```json
[
  {
    "command": "shapeless recipe",
    "ingredients": {
      "a": [
        "minecraft:water_bucket"
      ],
      "b": [
        "minecraft:glass_bottle"
      ]
    },
    "count": 1,
    "result": [
      "minecraft:potion",
      0,
      "{Potion:\"minecraft:water\"}"
    ]
  }
]
```

Note: while the empty bucket is returned, this is because its the default action of using a water bucket in a craft, there is at this point in time no way to specify additional items to be given back on a craft.

**Comment by ghost** [comment]
hmm... so you say you have to put a "\\". Okay. I already did it, but thanks for help.

**Comment by ghost** [comment]
and ah, reverse slashes are not visible in the texts here :) fixed my code right now to see in text format.
