### ISSUE TITLE
Request for additional Cappabilities

### ISSUE THREAD

**Issue by bookerthegeek** [ezterry/JsonRecipeEdit#3]
## Heyo ##
Just a quick thought, and question. Since your mod runs when it does, it is pretty well situated to also send IMC messages to other mods. There are more and more mods that are going the way of IMC for customization and it would be nice to have a program that can take a simple JSON file, and convert it into IMC to send to these mods. For example we have;
- [Thermal Expansion][1]
- [Tinkers Construct][2]

Just to name two of the major ones.
### Food for Thought ###
There was another mod for 1.7.x that performed the same feature, but he has no intention of updating it, and is will for another to take over. As I don't Java I don't know how hard it would be, but maybe some sort of integration of that mod into yours? [HERE][3] is the link to the other repository.

[1]:http://teamcofh.com/docs/thermal-expansion/other/inter-mod-communication/
[2]:https://github.com/SlimeKnights/TinkersConstruct#imc
[3]:https://github.com/Lunatrius/DynIMC/

**Comment by ezterry** [comment]
IMC interfaces are generally a bit limited use for jsonRecipeEdit, sometimes it could provide some additional useful interactions but many times it will not.  I may expose a way to call them when the json is parsed, however it will always remain unsupported unless the other mod author supports it.

This is because it will be as difficult for me to figure out the formatting of the IMC message, as making a new jsonRE command.  (and in many cases you will not have some of the required data, or be able to send the message at the correct point in system init)

To show you what such an interface might look like:

```json
[
  "IMC sample",
  {
    "command": "send imc",
    "mod": "<mod id>",
    "method": "<name of imc call>",
    "data": "<escaped nbt data as you would use in commands>"
  }
]
```

While it may look simple, the data is escaped like you would nbt data in commands, thus can be very elaborate when taking in account items, blocks, ect. (note escaped here means any time quotes are used inside the nbt string it needs to be prefixed with a '\\' so the json parser knows its part of the data string.  Also presently I know of no mod where I can send a test message that supports such a message while I'm actually parsing the json data (well after when TCon recommends I send the messages)

**Comment by bookerthegeek** [comment]
Gotcha. Thank you for looking into it, love your mod so far.
